### ISSUE TITLE
Extension Always Disabled on Clean VS Start

### ISSUE THREAD

**Issue by ghost** [madskristensen/TextGenerator#2]
I have an issue where the extension is always been disabled on a clean start of VS.

Very strange, enabling it from "extensions and updates" and restarting enables it.  But closing VS normally and then reopening again, its again disabled.

I am wondering if there is a conflict somewhere, So I have generated an activity log for VS and there are errors, what I cannot say is if there are related to this extension.

I hope this helps to identity the issue, I may be doing something wrong of maybe just some extensions don't work with each other, either way, I am hoping we can resolve it.

[ActivityLog.zip](https://github.com/madskristensen/TextGenerator/files/416358/ActivityLog.zip)

**Comment by madskristensen** [comment]
This should fix it https://github.com/remcoros/DuplicateExtensionFinder
